export enum EntitlementJustifications {
    MISSING_FEATURE = 'MISSING_FEATURE',
    MISSING_PERMISSION = 'MISSING_PERMISSION',
    PLAN_EXPIRED = 'PLAN_EXPIRED',
    MISSING_ROUTE = 'MISSING_ROUTE',
    ROUTE_DENIED = 'ROUTE_DENIED'
}