name: Pre Release

on:
  workflow_call:
    secrets:
      npm_token:
        required: true

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: generate NPMRC file
        run:
          echo "//registry.npmjs.org/:_authToken=${{ secrets.npm_token }}" > .npmrc

      - name: Install Dependencies
        run: "yarn"

      - name: Test Release
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_REPO_TOKEN }}
          GITHUB_HEAD_REF: $GITHUB_HEAD_REF
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_REPO_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > /home/runner/work/_temp/.npmrc
          npx semantic-release --dry-run --debug -b $GITHUB_HEAD_REF
