name: On Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches: [ master, next ]

jobs:
  lint:
    uses: ./.github/workflows/_lint.yaml
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}

  build-and-test:
    needs: lint
    uses: ./.github/workflows/_build-and-test.yaml
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}

  pre-release:
    needs: build-and-test
    uses: ./.github/workflows/_pre-release.yaml
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
